desarrollo_web/aplicaciones/erp/urls.py
"""
ESTE ARCHIVO SE CREA DENTRO DE UNA APLICACION PARA CREAR SUB-URLS
COMO EJEMPLO 127.0.0.1:8000/numero/uno  y 127.0.0.1:8000/numero/dos
"""

from django.urls import path
from aplicaciones.erp.views.category.views import *

# con [app_name] puedo darle una definicion mas especifica a los nombres de las url
# para diferenciar de que aplicacion viene ese nombre de url dentro de mi html poniendo un ejemplo --> 'erp:vista1'
app_name = 'erp'

urlpatterns = [
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category/form/', CategoryFormView.as_view(), name='category_form'),
]

desarrollo_web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from aplicaciones.homepage.views import IndexView
from aplicaciones.login.views import LoginFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('aplicaciones.erp.urls')),  # URL Para ingresar a las sub-url de la aplicacion [erp]

    # Son vistas de dos aplicaciones donde solo se hace una sola cosa por eso las ponemos directas en el urls principal
    path('', IndexView.as_view(), name='index'),  # Para acceder al Inicio de la Pagina Web
    path('login/', LoginFormView.as_view(), name='login'),  # Para acceder a la Pantalla de Logueo
]

desarrollo_web/templates/delete.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <!-- PRIMERA FORMA DE ENVIAR A TRAVÉS DE POST USANDO DJANGO, PERO SIN AGREGAR EL ATRIBUTO id="form_uno" -->
    <!-- LA SEGUNDA FORMA SERIA AGREGANDO EL ATRIBUTO id="form_uno" PARA MANDAR A LLAMAR EL METODO AJAX -->
    <form method="post" action="." id="form_uno">  <!-- conectamos a través del id a la funcion AJAX de hasta abajo -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}

                <!-- etiqueta invisible(hidden) usada en el metodo sobreescrito post -->
                <input type="hidden" name="action" value="{{ action }}">

                <!-- PRIMERA FORMA DE MOSTRAR MENSAJE DE ERROR OBTENIENDO EL ERROR USANDO DJANGO -->
                <!-- Mensaje Error color rojo -->
                {% if form.errors %}  <!-- Si detecta un error entra -->
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fas fa-ban"></i> Ha ocurrido un Error al querer guardar el registro</h5>
                    <ul>
                        <!-- Interando para obtener el/los error/es al agregar un registro nuevo -->
                        {% for field in form %}  <!-- obtenemos cada campo del formulario -->
                            {% for error in field.errors %}  <!-- y verificamos uno por uno para ver si ocurrio un error -->
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                <!-- /Fin de Mensaje de error -->
                <!-- /FIN DE LA PRIMERA FORMA USANDO DJANGO -->

                <div class="alert alert-danger alert-dismissible">
                      <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                      ¿Estas seguro de eliminar el registro N° {{ object.id }}?
                    </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-info btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>

    <script>
        <!-- FUNCION PARA ENVIAR A TRAVÉS DE POST LOS DATOS QUE OBTUVIMOS DENTRO DEL FORM DE ARRIBA CONECTADO CON LA VARIABLE id='form_uno' -->
    $('#form_uno').on('submit', function (e) {
        e.preventDefault();  <!-- indicamos que de una pausa, osea que no se recarge la pagina o redireccione a otra -->
        var parameters = $(this).serializeArray();  <!-- guarda todos los datos de cada campo del form en formato diccionario -->

        // SEGUNDO METODO PARA ENVIAR LOS DATOS DEL FORMULARIO DE ARRIBA CON DE AJAX A TRAVÉS DEL POST
        // DESDE LA URL A LA CLASE CREATE DENTRO DE VIEWS Y PARA REDIRECCIONAR A LA PAGINA list.html
        $.ajax({
            // url: '{% url 'erp:category_create' %}',  <!-- llama a la url que es la misma donde esta el boton-->
            url: window.location.pathname,  // obtener la dirección de la página actual (URL)
            type: 'POST',  <!-- Tipo Post porque se enviara un dato a traves de la url anterior -->
            data: parameters,  <!-- Aqui pones el dato que enviaremos, que solo envia el token de seguridad-->
            DataType: 'json'  <!-- Le indicamos el tipo de dato que estamos enviando -->
        }).done(function (data){ <!-- Esta Funcion o Metodo se va a ejecutar si la peticion es correcta -->
            <!-- Si no contiene algun mensaje de error la variable data entra en este if y nos regresa a la url indicada -->
            if(!data.hasOwnProperty('error')){
                // OBTIENE LA RUTA DE LA VARIABLE list_url QUE LA OBTENEMOS DE views.py DENTRO DE LA CLASE CategoryCreateView
                // Y SIRVE PARA REDIRECCIONAR A LA PAGINA DE LIST
                location.href = '{{ list_url }}';
                return false;
            }

            // SEGUNDA FORMA PARA MOSTRAR MENSAJE DE ERROR UTILIZANDO AJAX
            message_error(data.error);  <!-- Mandamos a llamar el archivo functions.js -->
            // /FIN DE LA LLAMA AL METODO DE LA SEGUNDA FORMA PARA MOSTRAR MENSAJE DE ERROR UTILIZANDO AJAX

        }).fail(function (jqXHR, textStatus, errorThrown){ <!-- Esta Funcion o Metodo se va a ejecutar cuando ocurre un error -->
            alert(textStatus + ': ' + errorThrown);
        }).always(function (data) {
            <!-- alert("complete");-->
        });
    });
    </script>

{% endblock content %}

desarrollo_web/templates/footer.html
<!-- Main Footer -->
  <footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020-2021 <a href="https://adminlte.io">Curso Django</a>.</strong><br>
    Todos los derechos reservados.
  </footer>

desarrollo_web/templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <!-- PRIMERA FORMA DE ENVIAR A TRAVÉS DE POST USANDO DJANGO, PERO SIN AGREGAR EL ATRIBUTO id="form_uno" -->
    <!-- LA SEGUNDA FORMA SERIA AGREGANDO EL ATRIBUTO id="form_uno" PARA MANDAR A LLAMAR EL METODO AJAX -->
    <form method="post" action="." id="form_uno">  <!-- conectamos a través del id a la funcion AJAX de hasta abajo -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}

                <!-- etiqueta invisible(hidden) usada en el metodo sobreescrito post para create y update-->
                <input type="hidden" name="action" value="{{ action }}">

                <!-- PRIMERA FORMA DE MOSTRAR MENSAJE DE ERROR OBTENIENDO EL ERROR USANDO DJANGO -->
                <!-- Mensaje Error color rojo -->
                {% if form.errors %}  <!-- Si detecta un error entra -->
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un Error al querer guardar el registro</h5>
                        <ul>
                            <!-- Interando para obtener el/los error/es al agregar un registro nuevo -->
                            {% for field in form %}  <!-- obtenemos cada campo del formulario -->
                                {% for error in field.errors %}  <!-- y verificamos uno por uno para ver si ocurrio un error -->
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <!-- /Fin de Mensaje de error -->
                <!-- /FIN DE LA PRIMERA FORMA USANDO DJANGO -->

                <!-- Hace la interacion para agregarlos dentro de la etiqueta de abajo [div] y [label] -->
                <!-- a cada campo de la tabla o modelo que ya tiene creado el formulario en el archivo-->
                <!-- forms.py y agregado atributos html tambien en el mismo form.py -->
                {% for field in form.visible_fields %} <!-- la variable visible_filds obtiene los campos en objetos uno por uno -->
                    <div class="form-group">
                        <label for="email">{{ field.label }}</label>
                        {{ field }}  <!-- vamos insertando cada campo obtenido de la interacion de arriba -->
                        <!-- OPCION 3 PARA AGREGAR ATRIBUTOS EXTRAS A CADA CAMPO CREADO POR FORM.PY -->
                        <!-- {{ field|add_class:'form-control'|attr:'autocomplete:off' }}-->
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar Registro
                </button>
            </div>
        </div>
    </form>

    <!-- Para Obtener Un mensaje PRO de ERROR utilizando SweetAlert2 -->
    <script>

    <!-- PRIMERA FORMA DE MOSTRAR MENSAJE DE ERROR OBTENIENDO EL ERROR USANDO DJANGO -->
    {% if form.errors %}  <!-- Si detecta un error entra e intera para hacer lo mismo que el mensaje creado arriba -->
        var errors = '';
        {% for field in form %}
            {% for error in field.errors %}
                errors+='{{ error }}\n';
            {% endfor %}
        {% endfor %}

        // Aqui estamos controlando este tipo de error --> (form.field_errors) interando entre los errores dentro de el
        {% for error in form.non_field_errors %}
            errors += '{{ error }}\n';
        {% endfor %}

        // Mensaje de Error
        Swal.fire({
          title: 'Error!',
          text: errors,
          icon: 'error'
        });
    {% endif %}
    <!-- /FIN DE LA PRIMERA FORMA USANDO DJANGO -->

    <!-- FUNCION PARA ENVIAR A TRAVÉS DE POST LOS DATOS QUE OBTUVIMOS DENTRO DEL FORM DE ARRIBA CONECTADO CON LA VARIABLE id='form_uno' -->
    /*$('#form_uno').on('submit', function (e) {
        e.preventDefault();  <!-- indicamos que de una pausa, osea que no se recarge la pagina o redireccione a otra -->
        var parameters = $(this).serializeArray();  <!-- guarda todos los datos de cada campo del form en formato diccionario -->

        // SEGUNDO METODO PARA ENVIAR LOS DATOS DEL FORMULARIO DE ARRIBA CON DE AJAX A TRAVÉS DEL POST
        // DESDE LA URL A LA CLASE CREATE DENTRO DE VIEWS Y PARA REDIRECCIONAR A LA PAGINA list.html
        $.ajax({
            // url: '{% url 'erp:category_create' %}',  <!-- llama a la url que es la misma donde esta el boton-->
            url: window.location.pathname,  // obtener la dirección de la página actual (URL)
            type: 'POST',  <!-- Tipo Post porque se enviara un dato a traves de la url anterior -->
            data: parameters,  <!-- Aqui pones el dato que enviaremos -->
            DataType: 'json'  <!-- Le indicamos el tipo de dato que estamos enviando -->
        }).done(function (data){ <!-- Esta Funcion o Metodo se va a ejecutar si la peticion es correcta -->
            <!-- Si no contiene algun mensaje de error la variable data entra en este if y nos regresa a la url indicada -->
            if(!data.hasOwnProperty('error')){
                // OBTIENE LA RUTA DE LA VARIABLE list_url QUE LA OBTENEMOS DE views.py DENTRO DE LA CLASE CategoryCreateView
                // Y SIRVE PARA REDIRECCIONAR A LA PAGINA DE LIST
                location.href = '{{ list_url }}';
                return false;
            }

            // SEGUNDA FORMA PARA MOSTRAR MENSAJE DE ERROR UTILIZANDO AJAX
            message_error(data.error);  <!-- Mandamos a llamar el archivo functions.js -->
            // /FIN DE LA LLAMA AL METODO DE LA SEGUNDA FORMA PARA MOSTRAR MENSAJE DE ERROR UTILIZANDO AJAX

        }).fail(function (jqXHR, textStatus, errorThrown){ <!-- Esta Funcion o Metodo se va a ejecutar cuando ocurre un error -->
            alert(textStatus + ': ' + errorThrown);
        }).always(function (data) {
            <!-- alert("complete");-->
        });
    });*/

    </script>

{% endblock content %}

desarrollo_web/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{{ title }}</title>
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.5/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.5/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- jQuery -->
  <script src="{% static 'lib/adminlte-3.0.5/plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'lib/adminlte-3.0.5/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'lib/adminlte-3.0.5/js/adminlte.min.js' %}"></script>
  <!-- SweetAlert2 -->
  <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>

  <script src="{% static 'js/functions.js' %}"></script>
  <!-- Block head el cual nos sirve para agregar mas librerias dependiendo de lo que se requiera en cada html -->
  {% block head %}

  {% endblock head %}
</head>
{% block body %}

{% endblock %}
</html>

desarrollo_web/templates/layout.html
<!-- HEREDO DE [vtc/body.html] para dar diseño vertical con sidebar y el head con lo basico en forma horizontal -->
<!-- HEREDO DE [hzt/body.html] para dar diseño horizontal del head normal sin el sidebar en vertical -->
{% extends 'vtc/body.html' %}

desarrollo_web/templates/list.html
{% extends 'layout.html' %}

{% load static %}

<!-- Este Bloque viene del home.html el cual hereda al body.html y por ende podemos usarlo aqui -->
{% block head %}
    <!-- Librerias de DATATABLES por JQUERY -->
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    <!-- Bloque para llamar a archivos estaticos que solo estaran dentro de la aplicacion erp -->
    {% block head_list %}

    {% endblock head_list %}

{% endblock head %}

{% block content %}
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="nombre_tabla_list">  <!-- en el id es con el que conectamos las funciones JQUERY, AJAX -->
                <thead>
                {% block columns %}

                {% endblock columns %}

                </thead>
                <tbody>
                {% block rows %}

                {% endblock rows %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">  <!-- dentro de class conectamos con "btnTest" hacia AJAX -->
                <i class="fas fa-plus"></i> Nuevo Registro
            </a>
        </div>
    </div>
{% endblock content %}


<!--Block javascript para indicar que cuando se carge la tabla se active automatiamente la configuracion de datatable,
    pero para esto se debe agregar las librerias de datatable y agregar las rutas hacia cada archivo static-->
{% block javascript %}
    <script>
        $(function () {

            <!-- Funcion para hacer tablas mas dinamicas -->
            $('#nombre_tabla_list').DataTable({
                responsive: true, <!--Para que se vaya adaptando mi tabla al tamaño de la pagina de una forma muy PRO XD-->
                autoWidth: false, <!--Para que respete el tamaño que yo le de a cada columna y no se auto ajuste-->

                <!-- Esta parte es para cambiar el idiamo al español a la adaptacion de realiza datatable a mi tabla -->
                <!-- mandando a llamar a la ruta de un txt donde esta el codigo&ndash;&gt;-->
                "language": {
                        url : '{% static 'lib/datatables-1.10.20/spanish.txt' %}'
                    }
            });

            <!-- Funcion para obtener registro/s de BD y enviarlos con el metodo POST en formato JSON -->
            <!-- Este codigo es para que cuando apretemos el boton al cual enlazamos a través de btnTest añadido en -->
            <!-- el parametro de class dentro del boton, podamos usar AJAX para actualizacion asincrona del boton -->
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'erp:category_list' %}',  <!-- llama a la url que es la misma donde esta el boton-->
                    type: 'POST',  <!-- Tipo Post porque se enviara un dato a traves de la url anterior -->
                    data: {id: 1},  <!-- Aqui pones el dato que enviaremos -->
                    DataType: 'json'  <!-- Le indicamos el tipo de dato que estamos enviando -->
                }).done(function (data){ <!-- Esta Funcion o Metodo se va a ejecutar si la peticion es correcta -->
                    console.log(data)
                }).fail(function (jqXHR, textStatus, errorThrown){ <!-- Esta Funcion o Metodo se va a ejecutar cuando ocurre un error -->
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                <!-- alert("complete");-->
                });
            });

        });
    </script>
{% endblock javascript %}